logging:
  file: ./logs/master.log
  level:
    kr.co.kware: INFO

batch.job.configuration.file.dir: target/config
batch.job.service.reaper.interval: 60000

spring:
  batch:
    initializer.enabled: false
    grid.size: 2 # slave size.
    admin.job.configuration.file.dir: target/config # /META-INF/spring/batch/bootstrap/integration/configuration-context.xml
    admin.job.service.reaper.interval: 60000

  activemq:
    brokerUrl: tcp://54.205.186.251:61616/
    # pooled: true
    user: admin
    password: admin

  datasource:
    platform: mysql
    initialize: false

    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    url: jdbc:mysql://kware.iptime.org:7777/internship
    driverClassName: com.mysql.jdbc.Driver
    username: kware
    password: kware1234
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true

  jpa:
    database: MYSQL
    openInView: false
    show_sql: true
    generate-ddl: false
    hibernate:
        ddl-auto: create-drop
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
